#!/usr/bin/python

import sys
from optparse import OptionParser
from ercore import ERcore
from ercore.fields import *
from ercore.materials import *
from ercore.shoreline import * 

usage = """

Usage: %prog [options] yaml_file tstart tend

tstart and tend can be:
 - datetime
 - ncep decimal time
 - string (%Y%m%d_%Hz or '%Y-%m-%d %H:%M:%S')

"""

parser = OptionParser(usage)

parser.add_option("-d", "--dt", dest="dt",help="Time step (seconds)",default=3600,type=float)

(options, args) = parser.parse_args()

if len(args)<3:
  print usage
  sys.exit(-1)

ercore=ERcore()
ercore.readYAML(args[0], namespace=globals())
ercore.run(args[1],args[2],options.dt)
